const CREATE_CODE = 201;
const BAD_REQUEST_CODE = 400;
const NOT_FOUND_CODE = 404;
const DEFAULT_CODE = 500;

module.exports = {
  CREATE_CODE,
  BAD_REQUEST_CODE,
  NOT_FOUND_CODE,
  DEFAULT_CODE,
};
